# Generated by Django 3.2.13 on 2022-05-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220504_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='deleted_at',
        ),
    ]
