# Generated by Django 3.2.13 on 2022-05-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_quiz', to='quiz.quiz')),
                ('detalle', models.CharField(max_length=250)),
                ('valoracion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('tiempo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'db_table': 'preguntas',
                'ordering': ['-id'],
            },
        ),
    ]
