# Generated by Django 3.2.13 on 2022-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='borrador',
            field=models.BooleanField(default=True),
        ),
    ]
