# Generated by Django 3.2.13 on 2022-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='nombre',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
