# Generated by Django 3.2.13 on 2022-05-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_pregunta', to='quiz.quiz'),
        ),
    ]
