# Generated by Django 3.2.13 on 2022-05-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0011_preguntas_posicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntas',
            options={'ordering': ['-posicion'], 'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.CreateModel(
            name='Elecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.BooleanField()),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_respuesta', to='quiz.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eleccion',
                'verbose_name_plural': 'elecciones',
                'db_table': 'elecciones',
                'ordering': ['-id'],
            },
        ),
    ]
