# Generated by Django 3.2.13 on 2022-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20220505_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='elecciones',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
