# Generated by Django 3.2.13 on 2022-05-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_elecciones_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecciones',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_respuesta', to='quiz.respuestas'),
        ),
    ]
