# Generated by Django 3.2.13 on 2022-05-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_elecciones_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elecciones',
            name='puntaje',
        ),
    ]
