# Generated by Django 3.2.13 on 2022-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_elecciones_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='elecciones',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
