# Generated by Django 3.2.13 on 2022-05-05 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0016_elecciones_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='elecciones',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_quiz', to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elecciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
