# Generated by Django 3.2.13 on 2022-05-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20220505_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elecciones',
            name='quiz',
        ),
        migrations.AddField(
            model_name='elecciones',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_pregunta', to='quiz.preguntas'),
        ),
    ]
