# Generated by Django 3.2.13 on 2022-05-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20220505_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='elecciones',
            name='quizpuntaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_respuesta', to='quiz.quiz'),
        ),
    ]
