# Generated by Django 3.2.13 on 2022-05-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_elecciones_quizpuntaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elecciones',
            old_name='quizpuntaje',
            new_name='quiz',
        ),
    ]
