# Generated by Django 3.2.13 on 2022-05-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_rename_quizpuntaje_elecciones_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecciones',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleccion_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
